name: Build & Deploy to Azure App Service

on:
  push:
    branches: [ "master" ]   # або "main"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # якщо .csproj у підпапці CollabHub/
      - name: Restore
        run: dotnet restore ./CollabHub/CollabHub.csproj

      - name: Build
        run: dotnet build ./CollabHub/CollabHub.csproj -c Release --no-restore

      - name: Publish
        run: dotnet publish ./CollabHub/CollabHub.csproj -c Release -o ./publish --no-build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: CollabHub20251104183826   # ТВОЄ точне ім’я Web App
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./publish
